package com.flowtest.API.repository;

import com.flowtest.API.model.NodeState;
import com.flowtest.API.model.GraphNode;
import com.flowtest.API.model.ExecutionStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import java.util.List;
import java.util.Optional;

@Repository
public interface NodeStateRepository extends JpaRepository<NodeState, String> {
    Optional<NodeState> findByNode(GraphNode node);
    List<NodeState> findByStatus(ExecutionStatus status);
    List<NodeState> findByIsAutoGenerated(boolean isAutoGenerated);
}

