package com.flowtest.API.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

@Data @Builder @NoArgsConstructor @AllArgsConstructor
@Entity
@Table(name = "node_states")
public class NodeState {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String stateId;

    @ManyToOne
    @JoinColumn(name = "node_id", nullable = false)
    private GraphNode node;

    @Enumerated(EnumType.STRING)
    private ExecutionStatus status;

    private LocalDateTime lastExecution;
    private int statusCode;

    @Column(columnDefinition = "TEXT")
    private String responseData;

    @Column(columnDefinition = "TEXT")
    private String storedParameters;

    private String errorMessage;
    private long executionTimeMs;
    private boolean isAutoGenerated;
    private int retryCount;
}
