package com.flowtest.API.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;
import java.util.Map;

@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class NodeState {
    private String nodeId;
    private ExecutionStatus status;
    private LocalDateTime lastExecution;
    private int statusCode;
    private Map<String, Object> responseData;
    private Map<String, Object> storedParameters;
    private String errorMessage;
    private long executionTimeMs;
    private boolean isAutoGenerated;
    private int retryCount;
}
