package com.flowtest.API.service;

import com.flowtest.API.model.*;
import com.flowtest.API.repository.GraphNodeRepository;
import com.flowtest.API.repository.NodeStateRepository;
import com.flowtest.API.repository.NodeExecutionResultRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.Optional;

@Slf4j
@Service
@RequiredArgsConstructor
@Transactional
public class ExecutionService {
    
    private final GraphNodeRepository nodeRepository;
    private final NodeStateRepository stateRepository;
    private final NodeExecutionResultRepository resultRepository;
    private final ParameterMappingService parameterMappingService;
    private final RestTemplate restTemplate;
    
    /**
     * Execute a single node (API endpoint)
     */
    public NodeExecutionResult executeNode(String nodeId, Map<String, Object> parameters) {
        log.info("Executing node: {}", nodeId);
        
        GraphNode node = nodeRepository.findById(nodeId)
                .orElseThrow(() -> new RuntimeException("Node not found: " + nodeId));
        
        long startTime = System.currentTimeMillis();
        NodeExecutionResult result;
        
        try {
            // Build HTTP request
            HttpHeaders headers = buildHeaders(node);
            String fullUrl = buildUrl(node, parameters);
            HttpEntity<?> requestEntity = new HttpEntity<>(parameters, headers);
            
            // Execute the API call
            ResponseEntity<Map> response = restTemplate.exchange(
                    fullUrl,
                    HttpMethod.valueOf(node.getMethod()),
                    requestEntity,
                    Map.class
            );
            
            long executionTime = System.currentTimeMillis() - startTime;
            
            // Create execution result
            result = NodeExecutionResult.builder()
                    .node(node)
                    .statusCode(response.getStatusCode().value())
                    .responseBody(response.getBody() != null ? response.getBody().toString() : "")
                    .rawResponseBody(response.getBody() != null ? response.getBody().toString() : "")
                    .executionTimeMs(executionTime)
                    .success(response.getStatusCode().is2xxSuccessful())
                    .executedAt(LocalDateTime.now())
                    .build();
            
            log.info("Node {} executed successfully in {} ms", nodeId, executionTime);
            
        } catch (Exception e) {
            long executionTime = System.currentTimeMillis() - startTime;
            
            result = NodeExecutionResult.builder()
                    .node(node)
                    .statusCode(500)
                    .errorMessage(e.getMessage())
                    .executionTimeMs(executionTime)
                    .success(false)
                    .executedAt(LocalDateTime.now())
                    .build();
            
            log.error("Node {} execution failed: {}", nodeId, e.getMessage());
        }
        
        // Save result
        result = resultRepository.save(result);
        
        // Update node state
        updateNodeState(node, result);
        
        return result;
    }
    
    /**
     * Execute node with skip option (for auto-generated nodes)
     */
    public NodeExecutionResult executeNodeWithSkip(String nodeId, Map<String, Object> parameters, boolean skipIfNeeded) {
        NodeState state = stateRepository.findByNode(
                nodeRepository.findById(nodeId)
                        .orElseThrow(() -> new RuntimeException("Node not found: " + nodeId))
        ).orElse(null);
        
        if (skipIfNeeded && state != null && state.isAutoGenerated() && state.getStatus() == ExecutionStatus.SUCCESS) {
            log.info("Skipping node {} - already executed successfully (auto-generated)", nodeId);
            return resultRepository.findByNodeOrderByExecutedAtDesc(
                    nodeRepository.findById(nodeId).get()
            ).get(0);
        }
        
        return executeNode(nodeId, parameters);
    }
    
    /**
     * Retry node execution
     */
    public NodeExecutionResult retryNode(String nodeId, Map<String, Object> parameters) {
        Optional<NodeState> state = stateRepository.findByNode(
                nodeRepository.findById(nodeId)
                        .orElseThrow(() -> new RuntimeException("Node not found: " + nodeId))
        );
        
        if (state.isPresent()) {
            state.get().setRetryCount(state.get().getRetryCount() + 1);
            stateRepository.save(state.get());
        }
        
        return executeNode(nodeId, parameters);
    }
    
    /**
     * Get execution results for a node
     */
    public java.util.List<NodeExecutionResult> getNodeExecutionHistory(String nodeId) {
        GraphNode node = nodeRepository.findById(nodeId)
                .orElseThrow(() -> new RuntimeException("Node not found: " + nodeId));
        return resultRepository.findByNodeOrderByExecutedAtDesc(node);
    }
    
    /**
     * Get all failed executions
     */
    public java.util.List<NodeExecutionResult> getFailedExecutions() {
        return resultRepository.findBySuccess(false);
    }
    
    /**
     * Build HTTP headers
     */
    private HttpHeaders buildHeaders(GraphNode node) {
        HttpHeaders headers = new HttpHeaders();
        headers.set("Content-Type", "application/json");
        
        if (node.isRequiresAuth()) {
            // TODO: Get auth config and add auth headers
            headers.set("Authorization", "Bearer token_placeholder");
        }
        
        return headers;
    }
    
    /**
     * Build full URL with parameters
     */
    private String buildUrl(GraphNode node, Map<String, Object> parameters) {
        String url = node.getPath();
        
        // Add query parameters for GET requests
        if ("GET".equalsIgnoreCase(node.getMethod()) && parameters != null && !parameters.isEmpty()) {
            StringBuilder query = new StringBuilder("?");
            parameters.forEach((key, value) -> 
                    query.append(key).append("=").append(value).append("&")
            );
            url += query.toString().replaceAll("&$", "");
        }
        
        return url;
    }
    
    /**
     * Update node state after execution
     */
    private void updateNodeState(GraphNode node, NodeExecutionResult result) {
        Optional<NodeState> existingState = stateRepository.findByNode(node);
        
        NodeState state;
        if (existingState.isPresent()) {
            state = existingState.get();
        } else {
            state = NodeState.builder()
                    .node(node)
                    .build();
        }
        
        state.setStatus(result.isSuccess() ? ExecutionStatus.SUCCESS : ExecutionStatus.FAILED);
        state.setLastExecution(result.getExecutedAt());
        state.setStatusCode(result.getStatusCode());
        state.setResponseData(result.getResponseBody());
        state.setErrorMessage(result.getErrorMessage());
        state.setExecutionTimeMs(result.getExecutionTimeMs());
        
        stateRepository.save(state);
    }
}

